// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolowItemHandler(arg1, arg2) {
  return window['go']['main']['App']['AddFolowItemHandler'](arg1, arg2);
}

export function FolowError(arg1) {
  return window['go']['main']['App']['FolowError'](arg1);
}

export function GetInventoryItems() {
  return window['go']['main']['App']['GetInventoryItems']();
}

export function GetItems() {
  return window['go']['main']['App']['GetItems']();
}

export function GetItemsOnSell() {
  return window['go']['main']['App']['GetItemsOnSell']();
}

export function GetMinPrice(arg1) {
  return window['go']['main']['App']['GetMinPrice'](arg1);
}

export function IsItemOnSale(arg1) {
  return window['go']['main']['App']['IsItemOnSale'](arg1);
}

export function PriceError() {
  return window['go']['main']['App']['PriceError']();
}

export function PutItemOnSale(arg1, arg2) {
  return window['go']['main']['App']['PutItemOnSale'](arg1, arg2);
}

export function RemoveItemFollow(arg1) {
  return window['go']['main']['App']['RemoveItemFollow'](arg1);
}

export function SetApiKey(arg1) {
  return window['go']['main']['App']['SetApiKey'](arg1);
}

export function SetItemPrice(arg1, arg2) {
  return window['go']['main']['App']['SetItemPrice'](arg1, arg2);
}

export function UpdateItems(arg1) {
  return window['go']['main']['App']['UpdateItems'](arg1);
}
