// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolowItemHandler(arg1:string,arg2:Array<{[key: string]: any}>):void;

export function FolowError(arg1:string):void;

export function GetInventoryItems():Promise<Array<any>>;

export function GetItems():Promise<Array<any>>;

export function GetItemsOnSell():Promise<Array<any>>;

export function GetMinPrice(arg1:string):Promise<number>;

export function IsItemOnSale(arg1:string):Promise<boolean>;

export function PriceError():void;

export function PutItemOnSale(arg1:string,arg2:number):Promise<string>;

export function RemoveItemFollow(arg1:string):void;

export function SetApiKey(arg1:string):Promise<any>;

export function SetItemPrice(arg1:string,arg2:number):void;

export function UpdateItems(arg1:Array<string>):void;
